blogs/urls.py
from django.urls import path
from blogs import views
from .views import CrearPublicacionView, EliminarPublicacionView, EditarPublicacionView

app_name = 'blogs'

urlpatterns = [
    path('', views.home_page),
    path('post/<slug:slug>', views.PostDetailView.as_view(), name='post'),
    path('featured/', views.FeaturedListView.as_view(), name='featured'),
    path('category/<slug:slug>', views.CategoryListView.as_view(), name='category'),
    path('search/', views.SearchResultsView.as_view(), name='search'),
    path('about/', views.about_me, name='about_me'),
    path('crear-publicacion/', CrearPublicacionView.as_view(), name='crear_publicacion'),
    path('eliminar-publicacion/<slug:slug>/', EliminarPublicacionView.as_view(), name='eliminar_publicacion'),
    path('editar-publicacion/<slug:slug>/', EditarPublicacionView.as_view(), name='editar_publicacion'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('blogs.urls')),
    path('', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from  django.urls import path
from django.views.generic import TemplateView

from users import views

app_name = 'users'

urlpatterns = [
    path('registration/', views.UserRegistration.as_view(), name='registration'),
    path('success/', TemplateView.as_view(template_name='users/success_registration.html'), name='success')
]

blogs/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    overview = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    categories = models.ManyToManyField('Category')
    featured = models.BooleanField(default=False)
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
    

    def get_absolute_url(self):
        return reverse("blogs:post", kwargs={"slug": self.slug})
    
    class Meta:
        ordering = ["-date_created"]
    
    def __str__(self):
        return self.title
    
class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse("blogs:category", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title
    

users/models.py
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    
    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

blogs/forms.py
from django import forms
from .models import Post

class PublicacionForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','slug', 'content']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = get_user_model()
        fields = ("username", "email", "password1", "password2")

blogs/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import generic
from django.db.models import Q
from django.views.generic.edit import CreateView, DeleteView
from .forms import PublicacionForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.urls import reverse
from django.views import View
from django.core.exceptions import PermissionDenied


from blogs.models import Post, Category

# Create your views here.

def home_page(request):
    posts = Post.objects.all()
    categories = Category.objects.all()
    featured = Post.objects.filter(featured=True)[:3]

    context = {
        'post_list' : posts,
        'categories' : categories,
        'featured' : featured,
    }

    return render(request, 'blogs/home_page.html', context=context)

class PostDetailView(generic.DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class FeaturedListView(generic.ListView):
    model = Post
    template_name = 'blogs/results.html'

    def get_queryset(self):
        query = Post.objects.filter(featured=True)
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context
    
class CategoryListView(generic.ListView):
    model = Post
    template_name = 'blogs/results.html'

    def get_queryset(self):
        query = self.request.path.replace('/category/', '')
        print(query)
        post_list = Post.objects.filter(categories__slug=query)
        return post_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context
    
class SearchResultsView(generic.ListView):
    model = Post
    template_name = 'blogs/results.html'

    def get_queryset(self):
        query = self.request.GET.get('search')
        post_list = Post.objects.filter(
            Q(title__icontains=query) | Q(categories__title__icontains=query)
        ).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


from django.shortcuts import render

def about_me(request):
    return render(request, 'about_me.html')

class CrearPublicacionView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PublicacionForm
    template_name = 'crear_publicacion.html'
    success_url = '/'
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    login_url = reverse_lazy('login')


class EliminarPublicacionView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'eliminar_publicacion_confirm.html'
    success_url = "/"
    
    def get_queryset(self):
        return self.model.objects.filter(author=self.request.user)
    



class EditarPublicacionView(LoginRequiredMixin, View):
    template_name = 'editar_publicacion.html'

    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        if post.author != request.user:
            raise PermissionDenied 
        form = PublicacionForm(instance=post)
        context = {'form': form, 'post': post}
        return render(request, self.template_name, context)

    def post(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        if post.author != request.user:
            raise PermissionDenied
        form = PublicacionForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect(reverse('blogs:post', kwargs={'slug': post.slug}))
        context = {'form': form, 'post': post}
        return render(request, self.template_name, context)
        

users/views.py
from django.views.generic.edit import FormView
from django.urls import reverse_lazy

from users.forms import RegisterForm

class UserRegistration(FormView):
    template_name = 'users/registration.html'
    form_class = RegisterForm
    success_url = reverse_lazy('users:success')

    def form_valid(self, form):
        form.save()
        return super(UserRegistration, self).form_valid(form)

blogs/templates/about_me.html
{% load static %}
{% load markdown_extras %}


<!DOCTYPE html>
<html>
<head>
    <title>Sobre mi</title>
</head>
<body>
    <h3>Informacion sobre mi</h3>
    <p>Mi nombre es Leandro Liset, tengo 29 años y soy nuevo en esto del mundo de la programacion, he hecho varias cosas en mi vida, desde trabajar en una empresa constructora, estudiar derecho y ultimamente dedicarme a los deportes electronicos.
        Me fue bastante bien esto ultimo, pero decidi tomarme un tiempo. La realidad es que me dieron ganas,
    de conocer un poco mas del mundo de la programacion, siempre estoy tratando de buscar nuevas herramientas para mi vida y me parecio que esta era una muy buena opcion. Siento que este es un ambiente lleno de cosas para aprender, tambien es bastante dificil he de reconocer, pero creo que con paciencia
    y un poco de buena voluntad puedo llegar a agarrarle la mano, aunque sea a alguno de los tantos lenguajes que existen.
        </p>

        <p>Gracias por leer, un saludo!</p>
</body>
</html>

blogs/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Blog</title>
    <link rel="icon" type="image/x-icon" href="/media/logo_adobe_express.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>

{% include "navbar.html" %}
{% block content %} {% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>
</html>

blogs/templates/blogs/featured.html
<div id="carouselIndicators" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        {% for f in featured %}
            <div class="carousel-item {% if f == featured|first %}active{% endif %}">
                <div class="px-5 p-md-5 mb-4 rounded text-bg-danger bg-gradient" style="height: 300px">
                    <div class="col-md-10 px-5 mx-5">
                        <h1 class="display-4 fw-bold px-5">{{ f.title }}</h1>
                        <p class="lead my-3 px-5">{{ f.overview }}</p>
                        <p class="lead mb-0 px-5"><a href="{{ f.get_absolute_url }}" class="text-white fw-bold">Continua
                            leyendo...</a></p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselIndicators"
            data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Anterior</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselIndicators"
            data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Siguiente</span>
    </button>
</div>

blogs/templates/blogs/home_page.html
{% extends 'base.html' %}

{% block content %} 
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">

    <main class="container">

        <div class="row g-5">
    
            <div class="col-md-12">
                {% include "blogs/featured.html" %}
            </div>
    
        </div>

        <div class="row g-5">
            <div class="col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border-bottom">
                    Más Artículos
                </h3>
                {% for post in post_list %}
                    <article class="blog-post">
                        <h2 class="blog-post-title mb-1">
                            <a href="{{ post.get_absolute_url }}" style="text-decoration: none"
                               class="text-black">
                                {{ post.title }}
                            </a>                         
                        </h2>
                        <p class="blog-post-meta">{{ post.date_created.date }}. {{post.author}}</p>
                        {% if user.is_authenticated and user == post.author %}
                        <form method="POST" action="{% url 'blogs:eliminar_publicacion' post.slug %}">
                            {% csrf_token %}
                        <h6><button type="submit">Eliminar Publicación</button></h6>
                        </form>
                        <form method="post" action="{% url 'blogs:editar_publicacion' post.slug %}">
                            {% csrf_token %}
                            <h6><button type="submit">Editar Publicación</button></h6>
                        </form>
                        {% endif %}                  
                        <hr>                       
                    </article>
                {% endfor %}
                          
            </div>

            <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                        <li><a href="{% url 'blogs:about_me' %}">Sobre mi</a></li>
                        <p class="mb-0">Información sobre el creador de esta página.</p>
                    </div>
                </div>
            </div>
        </div>

    </main>
</div>
{% endblock content %}

blogs/templates/blogs/post_detail.html
{% extends 'base.html' %}
{% load markdown_extras %}


{% block content %} 

<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">

    <main class="container">

        <div class="row g-5">
            <div class="col-md-12">

                <div class="row">
                    <div class="d-flex justify-content-between">
                        <h1>{{ post.title }}</h1>
                        <div class="align-self-end">Publicado: {{ post.date_created.date }}</div>
                    </div>
                </div>
                <hr class="d-none d-md-block my-2 mb-3 mt-2">
                {% if post.image %}
                    <div class="text-center">
                        <img src="{{ post.image.url }}" class="img-fluid" alt="image">
                    </div>
                {% endif %}

                <p>{{ post.content | markdown | safe }}</p>

            </div>
        </div>

    </main>
</div>
{% endblock content %} 

blogs/templates/blogs/results.html
{% extends 'base.html' %}

{% block content %} 
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">

    <main class="container">

        <div class="row g-5">
            <div class="col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border-bottom">
                    Destacados
                </h3>
                {% for post in post_list %}
                    <div class="card mb-3">
                        {% if post.image %}
                            <img src="{{ post.image.url }}" class="card-img-top" alt="thumbnail">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="card-text">{{ post.overview }}</p>
                            <p class="card-text"><small class="text-muted">Last updated {{ post.pub_date.date }}</small></p>
                        </div>
                    </div>
                {% endfor %}

            </div>

            <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                        <h4 class="fst-italic">Encontrados:</h4>
                        <p class="mb-0">{{ post_list|length }}</p>
                    </div>
                </div>
            </div>
        </div>

    </main>
</div>
{% endblock %}

blogs/templates/crear_publicacion.html
{% extends 'base.html' %}
{% load markdown_extras %}

{% block content %}
  <h2>Crear Nueva Publicación</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Crear Publicación</button>
  </form>
{% endblock %}

blogs/templates/editar_publicacion.html
{% extends 'base.html' %}

{% block content %}
<h1>Editar Publicación</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar Cambios</button>
</form>
{% endblock %}

blogs/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:featured' %}">Destacados</a>
                </li>           
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                       Categorías
                    </a>
                    <ul class="dropdown-menu">
                        {% for category in categories %}
                            <li><a class="dropdown-item"
                                   href="{% url 'blogs:category' category.slug %}">{{ category.title }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:crear_publicacion' %}">Crear Post</a>
                </li>
            </ul>
            <form class="d-flex" role="search" action="{% url 'blogs:search' %}" method="get">
                <input name="search" class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Buscar</button>
            </form>
            {% if user.is_authenticated %}
                <a class="btn btn-outline-primary ms-2" href="{% url 'logout' %}" role="button">Cerrar Sesión</a>
            {% else %}
                <a class="btn btn-outline-primary ms-2" href="{% url 'login' %}" role="button">Iniciar Sesión</a>
            {% endif %}
        </div>
    </div>
</nav>

users/templates/users/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">

    <main class="container">

        <div class="row g-5">
            <div class="col-md-3"></div>

            <div class="col-md-6">

                <div class="w-100 m-auto text-center">
                    <form method="POST" class="form-group">
                        {% csrf_token %}
                        {{ form|crispy}}
                        <button type="submit" class="btn btn-success">Register</button>
                    </form>
                </div>
            </div>

            <div class="col-md-3"></div>
        </div>

    </main>
</div>
{% endblock %}

users/templates/users/success_registration.html
{% extends 'base.html' %}

{% block content %}
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">

    <main class="container">

        <div class="row g-5">
            <div class="col-md-3"></div>

            <div class="col-md-6">

                <div class="w-100 m-auto text-center">
                    
                    <h1>Registro Exitoso</h1>
                    <a class="btn btn-outline-primary mb-5" href="{% url 'login' %}" role="button">Sign In</a>
                </div>
            </div>

            <div class="col-md-3"></div>
        </div>

    </main>
</div>
{% endblock %}